site_name: Project Documentation
site_description: Documentation as Code for REST API project
dev_addr: 127.0.0.1:8001
theme:
  name: material

nav:
  - Home: README.md
  - Overview: overview.md
  - Architecture:
      - SSD: architecture/SSD.md
      - SDD: architecture/SDD.md
      - ISD: architecture/ISD.md
  - Quality:
      - Test Strategy: quality/test-strategy.md
      - Traceability Matrix: quality/traceability-matrix.md
  - Governance:
      - Documentation Classification: governance/documentation-classification.md
      - Single Source of Truth: governance/single-source-of-truth.md
      - Versioning Policy: governance/versioning.md
  - API & Automation:
      - API OpenAPI: api/openapi.yaml
      - Swagger UI: api/swagger.html
      - UI Storybook: storybook.md
      - CI/CD Automation: ci-cd-docs.md
      - Definition of Done: definition-of-done.md
  - Review Questions:
      - Laboratory 7: lab7.md
      - Laboratory 8: lab8.md
      - Laboratory 9: lab9.md